# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-22 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0020_auto_20190122_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordatavalue',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=14, null=True),
        ),
    ]
