services:
  - docker
language: python
env:
  - COMPOSE_FILE=docker-compose.travis.yml

before_script:
  - docker version
  - docker-compose --version

script:
  - docker-compose build --pull
  - docker-compose up -d
  - sleep 5
  # - docker-compose exec web pytest --pylama
  - docker-compose exec web pytest
  - docker-compose run web pipchecker -r ../requirements.txt
