web:
  build: .
  command: "runserver 0.0.0.0:8000"
  environment:
      PYTHONUNBUFFERED: 0
      DJANGO_SETTINGS_MODULE: feinstaub.settings.base
  entrypoint:
   - './manage.py'
  links:
   - db
   - redis
  volumes:
   - .:/opt/code
  ports:
   - "8000:8000"
data:
  image: aexea/aexea-base
  volumes:
    - /home/uid1000
redis:
  image: redis
  ports:
    - "6379:6379"
db:
  image: postgres:9.4
